// <copyright file="RedirectService.cs" company="Moonrise Software, LLC">
// Copyright (c) Moonrise Software, LLC. All rights reserved.
// Licensed under the GNU Public License, Version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
// See https://github.com/MoonriseSoftwareCalifornia/CosmosCMS
// for more information concerning the license and the contributors participating to this project.
// </copyright>

namespace Sky.Editor.Services.Redirects
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Cosmos.Common.Data;
    using Cosmos.Common.Data.Logic;
    using Microsoft.EntityFrameworkCore;
    using Sky.Editor.Infrastructure.Time;
    using Sky.Editor.Services.Publishing;
    using Sky.Editor.Services.Slugs;

    /// <summary>
    /// Implements redirect management by storing redirects as special <see cref="Article"/> records (StatusCode = Redirect).
    /// </summary>
    public sealed class RedirectService : IRedirectService
    {
        private readonly ApplicationDbContext db;
        private readonly ISlugService slugs;
        private readonly IClock clock;
        private readonly IPublishingService publishedArtifactService;

        /// <summary>
        /// Initializes a new instance of the <see cref="RedirectService"/> class.
        /// </summary>
        /// <param name="db">EF Core database context.</param>
        /// <param name="slugs">Slug normalization service.</param>
        /// <param name="clock">Clock abstraction for consistent timestamps.</param>
        /// <param name="publishedArtifactService">Published artifact service.</param>
        public RedirectService(ApplicationDbContext db, ISlugService slugs, IClock clock, IPublishingService publishedArtifactService)
        {
            this.db = db;
            this.slugs = slugs;
            this.clock = clock;
            this.publishedArtifactService = publishedArtifactService;
        }

        /// <inheritdoc/>
        public async Task<Article> CreateOrUpdateRedirectAsync(string fromSlug, string toSlug, Guid userId)
        {
            fromSlug = slugs.Normalize(fromSlug);
            toSlug = slugs.Normalize(toSlug);

            // Do not redirect from root; silently ignore.
            if (fromSlug == "root")
            {
                return null;
            }

            // Allocate a new redirect article (new article number sequence entry).
            var maxArticleNumber = await db.ArticleNumbers.MaxAsync(m => m.LastNumber);

            var redirectJavaScript = new StringBuilder();
            redirectJavaScript.AppendLine("<script type=\"text/javascript\">");
            redirectJavaScript.AppendLine("  // Redirect script");
            redirectJavaScript.AppendLine("  window.location.href = '" + System.Net.WebUtility.HtmlEncode(toSlug) + "';");
            redirectJavaScript.AppendLine("</script>");
            redirectJavaScript.AppendLine("<noscript>");
            redirectJavaScript.AppendLine("<meta http-equiv=\"refresh\" content=\"0; url='" + System.Net.WebUtility.HtmlEncode(toSlug) + "'\" />");
            redirectJavaScript.AppendLine("</noscript>");

            var pageBody = new StringBuilder();
            pageBody.AppendLine("<h1>Redirecting to " + System.Net.WebUtility.HtmlEncode(toSlug) + "</h1>");
            pageBody.AppendLine("<p>If you are not redirected, click <a href=\"" + System.Net.WebUtility.HtmlEncode(toSlug) + "\">here</a>.</p>");
            pageBody.AppendLine("<p>Redirect generated by SkyCMS.</p>");


            var redirect = new Article
            {
                HeaderJavaScript = redirectJavaScript.ToString(),
                ArticleNumber = maxArticleNumber + 1,
                StatusCode = (int)StatusCodeEnum.Redirect,
                UrlPath = fromSlug.TrimEnd('/'),
                Title = fromSlug,
                Content = pageBody.ToString(),
                Published = clock.UtcNow,
                Updated = clock.UtcNow,
                VersionNumber = 1,
                UserId = userId.ToString(),
                BannerImage = string.Empty
            };

            db.Articles.Add(redirect);
            db.ArticleNumbers.Add(new ArticleNumber { LastNumber = redirect.ArticleNumber });
            await db.SaveChangesAsync();
            await publishedArtifactService.PublishAsync(redirect);
            return redirect;
        }
    }
}