
AWSTemplateFormatVersion: '2010-09-09'
Description: Static website on S3 with CloudFront (optional custom domain + ACM)

Parameters:
  DomainName:
    Type: String
    Default: ''
    Description: 'Optional: Fully qualified domain name (e.g., www.example.com). Leave empty to use the CloudFront default domain.'
  HostedZoneId:
    Type: String
    Default: ''
    Description: 'Optional: Route 53 Hosted Zone ID for DomainName. Required if DomainName is provided.'
  ACMCertificateArn:
    Type: String
    Default: ''
    Description: 'Optional: ACM certificate ARN for DomainName (must be in us-east-1). Required if DomainName is provided.'

Conditions:
  HasCustomDomain: !And
    - !Not [!Equals [!Ref DomainName, '']]
    - !Not [!Equals [!Ref HostedZoneId, '']]
    - !Not [!Equals [!Ref ACMCertificateArn, '']]

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Using static website hosting (index.html, error.html).
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      # Block direct public access; we will grant read via CloudFront (OAI) below.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Origin Access Identity to let CloudFront read the bucket without making it public.
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${AWS::StackName}'

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontReadViaOAI
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action:
              - s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'Static site for ${AWS::StackName}'
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        # If custom domain is provided, use aliases; otherwise none.
        Aliases: !If
          - HasCustomDomain
          - [!Ref DomainName]
          - !Ref 'AWS::NoValue'
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # AWS Managed Cache Policy (CachingOptimized)
        ViewerCertificate:
          # Use ACM certificate if provided; else the default CF certificate.
          AcmCertificateArn: !If [HasCustomDomain, !Ref ACMCertificateArn, !Ref 'AWS::NoValue']
          SslSupportMethod: !If [HasCustomDomain, 'sni-only', !Ref 'AWS::NoValue']
          MinimumProtocolVersion: !If [HasCustomDomain, 'TLSv1.2_2021', !Ref 'AWS::NoValue']
          CloudFrontDefaultCertificate: !If [HasCustomDomain, false, true]

  # Separate CloudFront distribution for the SkyCMS editor, using the same bucket but an origin path.
  CloudFrontDistributionEditor:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'SkyCMS Editor for ${AWS::StackName}'
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        Origins:
          - Id: S3OriginEditor
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            OriginPath: /editor
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: S3OriginEditor
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # AWS Managed Cache Policy (CachingOptimized)
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # Route 53 records (A + AAAA) only if a custom domain is used.
  DomainAliasRecordA:
    Type: AWS::Route53::RecordSet
    Condition: HasCustomDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        # CloudFront hosted zone ID is a well-known constant.
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false

  DomainAliasRecordAAAA:
    Type: AWS::Route53::RecordSet
    Condition: HasCustomDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: AAAA
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false

Outputs:
  CloudFrontURL:
    Description: 'CloudFront DNS name for the site (use this when you do not set a custom domain).'
    Value: !GetAtt CloudFrontDistribution.DomainName
  SiteURL:
    Description: 'Final URL: if custom domain is configured, this will be your domain; otherwise CloudFront URL.'
    Value: !If
      - HasCustomDomain
      - !Ref DomainName
      - !GetAtt CloudFrontDistribution.DomainName
  WebsiteBucketName:
    Description: 'Physical name of the S3 bucket for uploads from SkyCMS.'
    Value: !Ref WebsiteBucket
  CloudFrontDistributionId:
    Description: 'CloudFront distribution ID (useful for cache invalidations).' 
    Value: !Ref CloudFrontDistribution
  CloudFrontURLEditor:
    Description: 'CloudFront DNS name for the SkyCMS editor.'
    Value: !GetAtt CloudFrontDistributionEditor.DomainName
  CloudFrontDistributionIdEditor:
    Description: 'CloudFront distribution ID for the SkyCMS editor.'
    Value: !Ref CloudFrontDistributionEditor
