/**
 * Integration test that validates the actual JavaScript generated by the API
 */

const { describe, test, expect, beforeAll } = require('@jest/globals');

describe('Generated Contact API JavaScript', () => {
  beforeAll(() => {
    // In a real scenario, you would:
    // 1. Start the API server
    // 2. Fetch the script from /_api/contact/skycms-contact.js
    // 3. Execute it in a JSDOM environment
    
    // For now, we'll simulate the generated structure
    const generatedScript = `
/**
 * SkyCMS Contact Form API Client
 * Auto-generated with embedded configuration and antiforgery token
 */
(function(window) {
    'use strict';

    const SkyCmsContact = {
        config: {
            requireCaptcha: false,
            antiforgeryToken: 'test-antiforgery-token',
            submitEndpoint: '/_api/contact/submit',
            maxMessageLength: 5000,
            fieldNames: {
                name: 'name',
                email: 'email',
                message: 'message'
            }
        },

        init: function(formSelector, options) {
            const form = typeof formSelector === 'string' 
                ? document.querySelector(formSelector) 
                : formSelector;

            if (!form) {
                console.error('SkyCmsContact: Form not found');
                return;
            }

            const config = { 
                ...this.config, 
                ...options,
                fieldNames: { ...this.config.fieldNames, ...(options?.fieldNames || {}) }
            };

            form.addEventListener('submit', async (e) => {
                e.preventDefault();
                await this.handleSubmit(form, config);
            });
        },

        handleSubmit: async function(form, config) {
            const formData = new FormData(form);
            const fieldNames = config.fieldNames || this.config.fieldNames;
            
            const data = {
                name: formData.get(fieldNames.name),
                email: formData.get(fieldNames.email),
                message: formData.get(fieldNames.message)
            };

            return fetch(config.submitEndpoint, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'RequestVerificationToken': config.antiforgeryToken
                },
                body: JSON.stringify(data)
            });
        },

        loadCaptcha: function() {},
        getCaptchaToken: async function() { return ''; }
    };

    window.SkyCmsContact = SkyCmsContact;

})(window);
    `;

    // Execute the generated script in the Jest jsdom environment
    eval(generatedScript);
  });

  test('should create SkyCmsContact global object', () => {
    expect(window.SkyCmsContact).toBeDefined();
    expect(typeof window.SkyCmsContact).toBe('object');
  });

  test('should have all required methods', () => {
    expect(typeof window.SkyCmsContact.init).toBe('function');
    expect(typeof window.SkyCmsContact.handleSubmit).toBe('function');
    expect(typeof window.SkyCmsContact.loadCaptcha).toBe('function');
    expect(typeof window.SkyCmsContact.getCaptchaToken).toBe('function');
  });

  test('should have correct default configuration', () => {
    const config = window.SkyCmsContact.config;
    
    expect(config.submitEndpoint).toBe('/_api/contact/submit');
    expect(config.maxMessageLength).toBe(5000);
    expect(config.fieldNames).toBeDefined();
    expect(config.fieldNames.name).toBe('name');
    expect(config.fieldNames.email).toBe('email');
    expect(config.fieldNames.message).toBe('message');
  });

  test('should have antiforgery token embedded', () => {
    expect(window.SkyCmsContact.config.antiforgeryToken).toBeTruthy();
    expect(typeof window.SkyCmsContact.config.antiforgeryToken).toBe('string');
  });

  test('should initialize form successfully', () => {
    const form = document.createElement('form');
    form.id = 'testForm';
    document.body.appendChild(form);

    // Should not throw
    expect(() => {
      window.SkyCmsContact.init('#testForm');
    }).not.toThrow();
  });

  test('should support custom field names in initialization', () => {
    const form = document.createElement('form');
    form.id = 'customForm';
    document.body.appendChild(form);

    expect(() => {
      window.SkyCmsContact.init('#customForm', {
        fieldNames: {
          name: 'fullName',
          email: 'emailAddress',
          message: 'userMessage'
        }
      });
    }).not.toThrow();
  });
});
